### ISSUE TITLE
Uncaught Error: spawn ENOTDIR

### ISSUE THREAD

**Issue by ggranger** [yujinakayama/atom-lint#112]
Uncaught Error: spawn ENOTDIR

**Atom Version**: 0.158.0
**System**: Mac OS X 10.10.1
**Thrown From**: [atom-lint](https://github.com/yujinakayama/atom-lint) package, v0.20.0
### Steps To Reproduce
1. ...
2. ...
### Stack Trace

```
At child_process.js:1160

Error: spawn ENOTDIR
  at exports._errnoException (util.js:742:11)
  at ChildProcess.spawn (child_process.js:1160:11)
  at Object.exports.spawn (child_process.js:993:9)
  at CommandRunner.module.exports.CommandRunner.createChildProcess (/Users/guillaume/.atom/packages/atom-lint/lib/command-runner.coffee:48:21)
  at CommandRunner.module.exports.CommandRunner.runWithEnv (/Users/guillaume/.atom/packages/atom-lint/lib/command-runner.coffee:13:13)
  at CommandRunner.module.exports.CommandRunner.run (/Users/guillaume/.atom/packages/atom-lint/lib/command-runner.coffee:10:6)
  at Flake8.module.exports.Flake8.runFlake8 (/Users/guillaume/.atom/packages/atom-lint/lib/linter/flake8.coffee:22:12)
  at Flake8.module.exports.Flake8.run (/Users/guillaume/.atom/packages/atom-lint/lib/linter/flake8.coffee:13:6)
  at LintRunner.module.exports.LintRunner.lint (/Users/guillaume/.atom/packages/atom-lint/lib/lint-runner.coffee:78:12)
  at /Users/guillaume/.atom/packages/atom-lint/lib/lint-runner.coffee:63:10
  at TextBuffer.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/emissary/lib/emitter.js:118:15)
  at TextBuffer.module.exports.TextBuffer.saveAs (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:973:19)
  at TextBuffer.module.exports.TextBuffer.save (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:954:19)
  at TextEditor.module.exports.TextEditor.save (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:585:26)
  at Pane.module.exports.Pane.saveItem (/Applications/Atom.app/Contents/Resources/app/src/pane.js:511:16)
  at Pane.module.exports.Pane.saveActiveItem (/Applications/Atom.app/Contents/Resources/app/src/pane.js:501:19)
  at Workspace.module.exports.Workspace.saveActivePaneItem (/Applications/Atom.app/Contents/Resources/app/src/workspace.js:596:35)
  at atom-workspace.atom.commands.add.core:save (/Applications/Atom.app/Contents/Resources/app/src/workspace-element.js:287:30)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:243:29)
  at /Applications/Atom.app/Contents/Resources/app/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:549:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:391:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:167:20)

```

/cc @atom/core

**Comment by Moter8** [comment]
1. Execute `atom file.rb`
2. Copy in https://github.com/cinchrb/cinch#example and hit Ctrl+S
3. Get this error

---
```
atom 0.173.0-149cfdf

atom-lint  minimap  recent-files  recent-projects
```
```
 OS: Ubuntu 14.10 utopic
 Kernel: x86_64 Linux 3.16.0-29-generic
 Shell: fish
 DE: KDE5
 WM: KWin
```
---

```
/usr/local/share/atom/resources/app/src/workspace.js:624
Hide Stack Trace
Error: spawn ENOTDIR
  at exports._errnoException (util.js:746:11)
  at ChildProcess.spawn (child_process.js:1156:11)
  at Object.exports.spawn (child_process.js:989:9)
  at CommandRunner.module.exports.CommandRunner.createChildProcess (/home/carstenh/.atom/packages/atom-lint/lib/command-runner.coffee:48:21)
  at CommandRunner.module.exports.CommandRunner.runWithEnv (/home/carstenh/.atom/packages/atom-lint/lib/command-runner.coffee:13:13)
  at CommandRunner.module.exports.CommandRunner.run (/home/carstenh/.atom/packages/atom-lint/lib/command-runner.coffee:10:6)
  at Rubocop.module.exports.Rubocop.runRubocop (/home/carstenh/.atom/packages/atom-lint/lib/linter/rubocop.coffee:44:12)
  at Rubocop.module.exports.Rubocop.run (/home/carstenh/.atom/packages/atom-lint/lib/linter/rubocop.coffee:13:6)
  at LintRunner.module.exports.LintRunner.lint (/home/carstenh/.atom/packages/atom-lint/lib/lint-runner.coffee:78:12)
  at /home/carstenh/.atom/packages/atom-lint/lib/lint-runner.coffee:63:10
  at TextBuffer.module.exports.Emitter.emit (/usr/local/share/atom/resources/app/node_modules/emissary/lib/emitter.js:118:15)
  at TextBuffer.module.exports.TextBuffer.saveAs (/usr/local/share/atom/resources/app/node_modules/text-buffer/lib/text-buffer.js:977:19)
  at TextBuffer.module.exports.TextBuffer.save (/usr/local/share/atom/resources/app/node_modules/text-buffer/lib/text-buffer.js:958:19)
  at TextEditor.module.exports.TextEditor.save (/usr/local/share/atom/resources/app/src/text-editor.js:617:26)
  at Pane.module.exports.Pane.saveItem (/usr/local/share/atom/resources/app/src/pane.js:519:16)
  at Pane.module.exports.Pane.saveActiveItem (/usr/local/share/atom/resources/app/src/pane.js:508:19)
  at Workspace.module.exports.Workspace.saveActivePaneItemAndReportErrors (/usr/local/share/atom/resources/app/src/workspace.js:613:44)
  at Workspace.module.exports.Workspace.saveActivePaneItem (/usr/local/share/atom/resources/app/src/workspace.js:603:19)
  at atom-workspace.atom.commands.add.core:save (/usr/local/share/atom/resources/app/src/workspace-element.js:295:30)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/local/share/atom/resources/app/src/command-registry.js:243:29)
  at /usr/local/share/atom/resources/app/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/usr/local/share/atom/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:558:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/usr/local/share/atom/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:396:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/usr/local/share/atom/resources/app/src/window-event-handler.js:170:20)
```
