### ISSUE TITLE
Uncaught TypeError: Cannot read property 'lint' of null

### ISSUE THREAD

**Issue by sachanganesh** [yujinakayama/atom-lint#130]
1. Open SCSS file
2. Save SCSS file

**Atom Version**: 0.182.0
**System**: Microsoft Windows 8.1
**Thrown From**: [atom-lint](https://github.com/yujinakayama/atom-lint) package, v0.20.1
### Stack Trace

Uncaught TypeError: Cannot read property 'lint' of null

```
At C:\Users\Sachan Ganesh\.atom\packages\atom-lint\lib\linter\scss-lint.coffee:31

TypeError: Cannot read property 'lint' of null
  at SCSSLint.module.exports.SCSSLint.createViolationsFromXml (C:\Users\Sachan Ganesh\.atom\packages\atom-lint\lib\linter\scss-lint.coffee:31:22)
  at C:\Users\Sachan Ganesh\.atom\packages\atom-lint\lib\linter\xml-base.coffee:19:25
  at Parser.<anonymous> (C:\Users\Sachan Ganesh\.atom\packages\atom-lint\node_modules\xml2js\lib\xml2js.js:425:18)
  at Parser.emit (events.js:116:17)
  at Parser.exports.Parser.Parser.parseString (C:\Users\Sachan Ganesh\.atom\packages\atom-lint\node_modules\xml2js\lib\xml2js.js:434:14)
  at Parser.parseString (C:\Users\Sachan Ganesh\.atom\packages\atom-lint\node_modules\xml2js\lib\xml2js.js:6:61)
  at Object.exports.parseString (C:\Users\Sachan Ganesh\.atom\packages\atom-lint\node_modules\xml2js\lib\xml2js.js:476:19)
  at C:\Users\Sachan Ganesh\.atom\packages\atom-lint\lib\linter\xml-base.coffee:17:14
  at ChildProcess.<anonymous> (C:\Users\Sachan Ganesh\.atom\packages\atom-lint\lib\command-runner.coffee:32:7)
  at ChildProcess.emit (events.js:119:17)
  at maybeClose (child_process.js:1013:16)
  at Socket.<anonymous> (child_process.js:1181:11)
  at Socket.emit (events.js:116:17)
  at Pipe.close (net.js:477:12)

```
### Commands

```
     -1:50.2 settings-view:open (atom-workspace.workspace.scrollbars-visible-always.theme-monokai.theme-one-dark-ui)
  2x -1:08.2 editor:newline (atom-text-editor.editor)
  6x -1:04.2 core:backspace (atom-text-editor.editor)
     -1:01.0 editor:newline (atom-text-editor.editor)
  4x -0:58.5 core:backspace (atom-text-editor.editor)
     -0:37.5 autocomplete-plus:confirm (atom-text-editor.editor)
     -0:35.2 editor:newline (atom-text-editor.editor)
 14x -0:34.5 core:backspace (atom-text-editor.editor)
     -0:32.0 editor:newline (atom-text-editor.editor)
  2x -0:06.6 core:save (atom-text-editor.editor)
```
### Config

``` json
{
  "core": {
    "autoHideMenuBar": true,
    "themes": [
      "one-dark-ui",
      "monokai"
    ],
    "ignoredNames": [
      ".git",
      ".DS_Store",
      "*.class",
      "*.out"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
atom-lint, v0.20.1
autocomplete-plus, v2.1.6
color-picker, v1.4.4
language-haml, v0.15.0
language-jade, v0.3.0
language-scala, v1.1.0
linter-javac, v0.1.3
linter-scalac, v0.3.3
monokai, v0.12.0
slim-language, v2.0.0

# Dev
No dev packages
```

**Comment by RPDeshaies** [comment]
:+1:

**Comment by megheaiulian** [comment]
:thumbsup:

**Comment by oswaldoacauan** [comment]
:+1:
