### ISSUE TITLE
Uncaught Error: Severity must be any of warning,error. info is passed.

### ISSUE THREAD

**Issue by dotmilk** [yujinakayama/atom-lint#131]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 0.182.0
**System**: Mac OS X 10.10.2
**Thrown From**: [atom-lint](https://github.com/yujinakayama/atom-lint) package, v0.20.1
### Stack Trace

Uncaught Error: Severity must be any of warning,error. info is passed.

```
At events.js:94

Error: Severity must be any of warning,error. info is passed.
  at new Violation (/Users/emris/.atom/packages/atom-lint/lib/violation.coffee:12:17)
  at JsHint.module.exports.JsHint.createViolationFromElement (/Users/emris/.atom/packages/atom-lint/lib/linter/jshint.coffee:33:9)
  at JsHint.module.exports.XmlBase.createViolationsFromXml (/Users/emris/.atom/packages/atom-lint/lib/linter/xml-base.coffee:30:8)
  at /Users/emris/.atom/packages/atom-lint/lib/linter/xml-base.coffee:19:25
  at Parser.<anonymous> (/Users/emris/.atom/packages/atom-lint/node_modules/xml2js/lib/xml2js.js:384:20)
  at Parser.emit (events.js:116:17)
  at Object.onclosetag (/Users/emris/.atom/packages/atom-lint/node_modules/xml2js/lib/xml2js.js:348:26)
  at emit (/Users/emris/.atom/packages/atom-lint/node_modules/xml2js/node_modules/sax/lib/sax.js:615:33)
  at emitNode (/Users/emris/.atom/packages/atom-lint/node_modules/xml2js/node_modules/sax/lib/sax.js:620:3)
  at closeTag (/Users/emris/.atom/packages/atom-lint/node_modules/xml2js/node_modules/sax/lib/sax.js:861:5)
  at Object.write (/Users/emris/.atom/packages/atom-lint/node_modules/xml2js/node_modules/sax/lib/sax.js:1294:29)
  at Parser.exports.Parser.Parser.parseString (/Users/emris/.atom/packages/atom-lint/node_modules/xml2js/lib/xml2js.js:403:31)
  at Parser.parseString (/Users/emris/.atom/packages/atom-lint/node_modules/xml2js/lib/xml2js.js:6:61)
  at Object.exports.parseString (/Users/emris/.atom/packages/atom-lint/node_modules/xml2js/lib/xml2js.js:433:19)
  at /Users/emris/.atom/packages/atom-lint/lib/linter/xml-base.coffee:17:14
  at ChildProcess.<anonymous> (/Users/emris/.atom/packages/atom-lint/lib/command-runner.coffee:32:7)
  at ChildProcess.emit (events.js:119:17)
  at maybeClose (child_process.js:1013:16)
  at Process.ChildProcess._handle.onexit (child_process.js:1085:5)

```
### Commands

```
     -0:45.5 tree-view:toggle (atom-text-editor.editor)
```
### Config

``` json
{
  "core": {
    "themes": [
      "seti-ui",
      "seti-syntax"
    ],
    "audioBeep": false
  }
}
```
### Installed Packages

``` coffee
# User
alignment, v1.1.4
atom-lint, v0.20.1
auto-detect-indentation, v0.3.0
autoclose-html, v0.15.0
color-picker, v1.4.4
language-applescript, v0.1.0
language-jade, v0.3.0
language-lisp, v0.1.1
language-puppet, v0.10.0
language-r, v0.1.1
language-swift, v0.3.0
line-ending-converter, v1.0.0
meteor-api, v2.12.0
preview-tabs, v0.1.6
seti-syntax, v0.3.3
seti-ui, v0.6.3
space-tab, v0.1.0

# Dev
No dev packages
```

**Comment by skoblenick** [comment]
I can reproduce this error just by open/saving the file below in Atom 0.187.0 with atom-lint 0.20.1

https://github.com/scottksmith95/beerlocker/blob/master/beerlocker-6.2/controllers/oauth2.js
