### ISSUE TITLE
Failed to activate the atom-lint package

### ISSUE THREAD

**Issue by heragu** [yujinakayama/atom-lint#144]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 0.187.0
**System**: Mac OS X 10.9.5
**Thrown From**: [atom-lint](https://github.com/yujinakayama/atom-lint) package, v0.20.1
### Stack Trace

Failed to activate the atom-lint package

```
At Cannot read property 'previous' of undefined

TypeError: Cannot read property 'previous' of undefined
  at /Users/DanielH/.atom/packages/atom-lint/lib/atom-lint.coffee:37:59
  at Config.module.exports.Config.observeKeyPath (/Applications/Atom.app/Contents/Resources/app/src/config.js:621:7)
  at Config.module.exports.Config.observe (/Applications/Atom.app/Contents/Resources/app/src/config.js:133:21)
  at Function.module.exports.Config.observe (/Users/DanielH/.atom/packages/atom-lint/lib/config.coffee:25:17)
  at Object.module.exports.enable (/Users/DanielH/.atom/packages/atom-lint/lib/atom-lint.coffee:36:34)
  at Object.module.exports.activate (/Users/DanielH/.atom/packages/atom-lint/lib/atom-lint.coffee:17:6)
  at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app/src/package.js:240:19)
  at /Applications/Atom.app/Contents/Resources/app/src/package.js:221:30
  at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app/src/package.js:167:15)
  at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app/src/package.js:214:14)
  at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:465:21)
  at /Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-manager.js:226:29
  at exit (/Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-manager.js:43:16)
  at BufferedProcess.triggerExitCallback (/Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:63:47)
  at /Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:77:18
  at Socket.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:150:18)
  at Socket.emit (events.js:138:20)
  at Pipe.close (net.js:477:12)

```
### Commands

```
     -0:22.0 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-atom-dark-syntax.theme-atom-dark-ui)
```
### Config

``` json
{
  "core": {
    "disabledPackages": [
      "jshint",
      "jslint"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
atom-handlebars, v0.3.38
atom-jshint, v1.4.3
atom-lint, v0.20.1
linter-rubocop, v0.2.2

# Dev
No dev packages
```

**Comment by ee0pdt** [comment]
Any thoughts on fixing this? I have same issue on fresh install of Atom on Mac OS X 10.10.3

**Comment by paltman** [comment]
This is happening for me as well.

**Comment by BlakeTurner** [comment]
Me too.

**Comment by tangshiyu** [comment]
how to save it?
